#
# Copyright (c) 2015 - 2016 SuperDream Inc. <http://www.superdream.me>
#

spring:
  # 数据源配置
  datasource:
     apis:
        driverClassName: "com.mysql.jdbc.Driver"
        jdbcUrl: "jdbc:mysql://localhost/demo1?useUnicode=true&characterEncoding=utf8&useNewIO=true"
        username: "root"
        password: "123456"
    # HikariCP属性配
        maximumPoolSize: 20
        minimumIdle: 10
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        connectionTestQuery: "select 1"
        connectionInitSql: "set names utf8mb4"
     user:
        driver-class-name: "com.mysql.jdbc.Driver"
        jdbcUrl: "jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf8&useNewIO=true"
        username: "root"
        password: "123456"
    # HikariCP属性配置
        maximumPoolSize: 20
        minimumIdle: 10
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        connectionTestQuery: "select 1"
        connectionInitSql: "set names utf8mb4"
 # Http配置
  http:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
  # MVC配置
  mvc:
    favicon:
      enabled: false

  # 静态资源配置
  resources:
    add-mappings: true

#  jackson:
#    date-format: "YYYY-MM-dd HH:mm:ss"
#    jodaDateTimeFormat: "YYYY-MM-dd HH:mm:ss"
#    time-zone: Asia/Shanghai
#    serialization:
#      write_dates_as_timestamps: true


  redis:
# 集群配置
#    cluster:
#          nodes:
#            - 192.168.0.17:6390
#            - 192.168.0.17:6391
#            - 192.168.0.17:6392
#            - 192.168.0.9:6390
#            - 192.168.0.9:6391
#            - 192.168.0.9:6392
    database: 0
    host: 192.168.137.128
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 10
      max-wait: -1

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 80

